@host = 127.0.0.1:8089 

GET http://{{host}}/api/v1/users/kebab3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgiLCJuYW1lIjoia2ViYWJpazMiLCJleHAiOjE2Njc4NTI0NDh9.0DdXZz9mk71Q-OtCNDN20RB-A1RVVGYKxPpIGRGTHHw

